services:
  mailwizz-v2-mailserver:
    container_name: mailwizz-v2-mailserver
    image: axllent/mailpit
    ports:
      - target: 1025
        published: 1025
        protocol: tcp
      - target: 8025
        published: 8025
        protocol: tcp
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      mailwizz:

  mailwizz-v2-redis:
    image: redis:latest
    container_name: mailwizz-v2-redis
    ports:
      - "6379:6379"
    networks:
      mailwizz:

  mailwizz-v2-mysql:
    image: mysql:5.7
    container_name: mailwizz-v2-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mailwizz-v2
      - MYSQL_DATABASE=mailwizz-v2
      - MYSQL_USER=mailwizz-v2
      - MYSQL_PASSWORD=mailwizz-v2
      - MYSQL_PORT=3306
      - MYSQL_HOST=localhost
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mailwizz-v2-test.sh:/docker-entrypoint-initdb.d/mailwizz-v2-test.sh
    networks:
      mailwizz:

  mailwizz-v2-webserver:
    image: nginx:alpine
    container_name: mailwizz-v2-webserver
    volumes:
      - ./web:/var/www/web
      - ./docker/ssl:/etc/nginx/ssl
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - mailwizz-v2-php
    networks:
      mailwizz:
        aliases:
          - mailwizz.test

  mailwizz-v2-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile-php7.2
    container_name: mailwizz-v2-php
    volumes:
      - ./web:/var/www/web
      - ./docker/pack:/var/www/pack
      - ./docker/phpstan:/var/www/phpstan
      - ./docker/phpcsfixer:/var/www/phpcsfixer
      - ./docker/phpunit:/var/www/phpunit
      - ./docker/php/conf.d/00-user.ini:/etc/php/7.2/fpm/conf.d/00-user.ini
    links:
      - mailwizz-v2-mysql
      - mailwizz-v2-mailserver
      - mailwizz-v2-redis
    environment:
      INSIDE_DOCKER: 1
      MW_DEVELOPMENT: 1
    networks:
      mailwizz:

  mailwizz-v2-reverse-proxy:
    image: nginx:alpine
    container_name: mailwizz-v2-reverse-proxy
    volumes:
      - ./docker/ssl:/etc/nginx/ssl
      - ./docker/nginx/nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    links:
      - mailwizz-v2-webserver
    networks:
      mailwizz:

  mailwizz-v2-haproxy:
    image: haproxy:2.3
    container_name: mailwizz-v2-haproxy
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "8081:8081"
    links:
      - mailwizz-v2-webserver
    networks:
      mailwizz:

  mailwizz-v2-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mailwizz-v2-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mailwizz-v2-mysql
    ports:
      - "81:80"
    volumes:
      - /sessions
    links:
      - mailwizz-v2-mysql
    networks:
      mailwizz:

volumes:
  esdata7:
    driver: local

networks:
  mailwizz:
